version: "2"

services:

  postgres:
    image: postgres:9.5
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong

  ag_node:
    image: ag_node:latest
    container_name: ag_node
#    depends_on:
#      - kong-ee
#      - app
    restart: always
    ports:
      - 4200:80

  kong:
      image: kong:0.14.1
      container_name: kong
      depends_on:
        - postgres
      restart: always
      ports:
        - 80:8000
        - 8001:8001
        - 443:8443
        - 8444:8444
      command: "kong start --run-migrations " #
      environment:
  #      - KONG_ENFORCE_RBAC=on
  #      - KONG_RBAC_INITIAL_ADMIN_PASS=foo
  #      - KONG_LOG_LEVEL=debug
  #      - KONG_PORTAL=on
        - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl
  #      - KONG_PORTAL_API_URI=0.0.0.0:8000/portal
  #      - KONG_PORTAL_GUI_URI=localhost:8003
        - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
  #      - KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444
        - KONG_DATABASE=postgres
        - KONG_PG_HOST=postgres
  #      - KONG_LICENSE_DATA=${KONG_LICENSE_DATA}
  #      - KONG_VITALS=on
  #      - KONG_ANONYMOUS_REPORTS=off
      volumes:
        - ./etc/kong:/etc/kong
        - ./ssl:/usr/local/kong/ssl

  app:
    image: app:latest
    container_name: app
    depends_on:
      - mongo1
    restart: always
    ports:
      - 5000:5000

  mongo1:
    container_name: mongo1
    image: mongo:3.6
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"


